### ISSUE TITLE
Build Problem

### ISSUE THREAD

**Issue by okproject** [michaellperry/PharmaNet#1]
Hi.

I am trying to build Sales project.

First it tries to restore nugets. 
Nuget restore failed.
Then these error listed.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to find version '1.0.3' of package 'PharmaNet.Infrastructure.Repository'.	PharmaNet.Sales.Application			
Error		Unable to find version '1.0.3' of package 'PharmaNet.Infrastructure.Repository'.	PharmaNet.Sales.SQL			
Error		Unable to find version '1.0.3' of package 'PharmaNet.Infrastructure.Repository'.	PharmaNet.Sales.Subscriber			
Error		Unable to find version '1.0.10' of package 'PharmaNet.Infrastructure.Messaging'.	PharmaNet.Sales.Subscriber			
Error		Unable to find version '1.0.1' of package 'PharmaNet.Infrastructure.SQL'.	PharmaNet.Sales.SQL			
Error		Unable to find version '1.0.1' of package 'PharmaNet.Infrastructure.SQL'.	PharmaNet.Sales.Subscriber			
Error		Unable to find version '1.0.1' of package 'PharmaNet.Fulfillment.Messages'.	PharmaNet.Sales.Subscriber			
Error		The command ""C:\temp\PharmaNet\Sales\.nuget\nuget.exe" install "C:\temp\PharmaNet\Sales\PharmaNet.Sales.Subscriber\packages.config" -source ""  -RequireConsent -o "C:\temp\PharmaNet\Sales\packages"" exited with code 1.	PharmaNet.Sales.Subscriber			
Error		The command ""C:\temp\PharmaNet\Sales\.nuget\nuget.exe" install "C:\temp\PharmaNet\Sales\PharmaNet.Sales.SQL\packages.config" -source ""  -RequireConsent -o "C:\temp\PharmaNet\Sales\packages"" exited with code 1.	PharmaNet.Sales.SQL			
Error		The command ""C:\temp\PharmaNet\Sales\.nuget\nuget.exe" install "C:\temp\PharmaNet\Sales\PharmaNet.Sales.Application\packages.config" -source ""  -RequireConsent -o "C:\temp\PharmaNet\Sales\packages"" exited with code 1.	PharmaNet.Sales.Application			
Error		One or more errors occurred.	PharmaNet.Sales.SQL			
Error		One or more errors occurred.	PharmaNet.Sales.Subscriber			
Error		NuGet Package restore failed for project PharmaNet.Sales.Subscriber: Unable to find version '1.0.3' of package 'PharmaNet.Infrastructure.Repository'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'PharmaNet.Infrastructure.Repository.1.0.3' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'PharmaNet.Infrastructure.Repository.1.0.3' is not found on source 'https://api.nuget.org/v3/index.json'.
  https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/: Package 'PharmaNet.Infrastructure.Repository.1.0.3' is not found on source 'https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/'.
.			0	
Error		NuGet Package restore failed for project PharmaNet.Sales.Subscriber: Unable to find version '1.0.10' of package 'PharmaNet.Infrastructure.Messaging'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'PharmaNet.Infrastructure.Messaging.1.0.10' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'PharmaNet.Infrastructure.Messaging.1.0.10' is not found on source 'https://api.nuget.org/v3/index.json'.
  https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/: Package 'PharmaNet.Infrastructure.Messaging.1.0.10' is not found on source 'https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/'.
.			0	
Error		NuGet Package restore failed for project PharmaNet.Sales.Subscriber: Unable to find version '1.0.1' of package 'PharmaNet.Infrastructure.SQL'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'PharmaNet.Infrastructure.SQL.1.0.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'PharmaNet.Infrastructure.SQL.1.0.1' is not found on source 'https://api.nuget.org/v3/index.json'.
  https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/: Package 'PharmaNet.Infrastructure.SQL.1.0.1' is not found on source 'https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/'.
.			0	
Error		NuGet Package restore failed for project PharmaNet.Sales.Subscriber: Unable to find version '1.0.1' of package 'PharmaNet.Fulfillment.Messages'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'PharmaNet.Fulfillment.Messages.1.0.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'PharmaNet.Fulfillment.Messages.1.0.1' is not found on source 'https://api.nuget.org/v3/index.json'.
  https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/: Package 'PharmaNet.Fulfillment.Messages.1.0.1' is not found on source 'https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/'.
.			0	
Error		NuGet Package restore failed for project PharmaNet.Sales.SQL: Unable to find version '1.0.3' of package 'PharmaNet.Infrastructure.Repository'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'PharmaNet.Infrastructure.Repository.1.0.3' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'PharmaNet.Infrastructure.Repository.1.0.3' is not found on source 'https://api.nuget.org/v3/index.json'.
  https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/: Package 'PharmaNet.Infrastructure.Repository.1.0.3' is not found on source 'https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/'.
.			0	
Error		NuGet Package restore failed for project PharmaNet.Sales.SQL: Unable to find version '1.0.1' of package 'PharmaNet.Infrastructure.SQL'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'PharmaNet.Infrastructure.SQL.1.0.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'PharmaNet.Infrastructure.SQL.1.0.1' is not found on source 'https://api.nuget.org/v3/index.json'.
  https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/: Package 'PharmaNet.Infrastructure.SQL.1.0.1' is not found on source 'https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/'.
.			0	
Error		NuGet Package restore failed for project PharmaNet.Sales.Application: Unable to find version '1.0.3' of package 'PharmaNet.Infrastructure.Repository'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'PharmaNet.Infrastructure.Repository.1.0.3' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'PharmaNet.Infrastructure.Repository.1.0.3' is not found on source 'https://api.nuget.org/v3/index.json'.
  https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/: Package 'PharmaNet.Infrastructure.Repository.1.0.3' is not found on source 'https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/'.
.			0

**Comment by michaellperry** [comment]
I didn't make it very clear, but the projects depend upon each other via NuGet packages. You will need to build the projects, create the packages, and then set up a package source.

![pharmanet](https://cloud.githubusercontent.com/assets/68170/25768857/2d84481e-31d2-11e7-8ce4-6ad8f711cefa.png)

First build the Infrastructure project. Then open a command line in the "Package" folder and cd to each of the sub folders to execute "nuget pack". Then copy each of the resulting package files to new folder, for example "C:\Packages"

Then do the same for Fulfillment. Once you have all of these package files, then add C:\Packages to "Package Sources" in Visual Studio (Tools, Options, NuGet Package Manager), and you can build Sales.

In practice, I typically set up a CI environment to build all of the NuGet packages and deploy them to a private repository. Then different teams can publish their message APIs and take dependencies as they need them.

Hope this helps.
